# Generated by Django 4.0.4 on 2022-05-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividends.company'),
        ),
    ]
