# Generated by Django 4.0.4 on 2022-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0003_rename_amount_stock_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='number_of_shares',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
