# Generated by Django 4.0.4 on 2022-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0004_stock_currency_stock_number_of_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='number_of_shares',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
